import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-pink-600 text-white py-4 shadow">
          <div className="container mx-auto flex justify-between items-center px-4">
            <h1 className="text-2xl font-bold">My NextJS App</h1>
            <nav>
              <ul className="flex gap-6">
                <li>
                  <Link href="/" className="hover:underline">Home</Link>
                </li>
                <li>
                  <Link href="/blog" className="hover:underline">Blog</Link>
                </li>
                <li>
                  <Link href="/contact" className="hover:underline">Contact</Link>
                </li>
                <li>
                  <Link href="/products" className="hover:underline">Products</Link>
                </li>
                <li>
                  <Link href="/login" className="hover:underline">Login</Link>
                </li>
              </ul>
            </nav>
          </div>
        </header>

        {/* Main content */}
        <main className="flex-1 container mx-auto px-4 py-8">{children}</main>
        {/* {children} */}

        {/* Footer */}
        <footer className="bg-gray-200 text-center py-4 mt-8">
          <span className="text-gray-600">© 2025 My NextJS App. All rights reserved.</span>
        </footer>
        
      </body>
    </html>
  );
}


